version: '3'

services:
  kong:
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - kong-container
    container_name: kong
    image: kong
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-db
    depends_on:
      - kong-migrate
    restart: on-failure:3

  kong-migrate:
    image: kong
    depends_on:
      - kong-db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-container
      - KONG_PG_USER=$KONG_POSTGRES_USER
      - KONG_PG_PASSWORD=$KONG_POSTGRES_PASSWORD
      - KONG_CASSANDRA_CONTACT_POINTS=kong-db
    command: "kong migrations bootstrap"
    restart: on-failure:3

  kong-db:
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - kong-db-container
    container_name: kong-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=$KONG_POSTGRES_DB
      - POSTGRES_USER=$KONG_POSTGRES_USER
      - POSTGRES_PASSWORD=$KONG_POSTGRES_PASSWORD
    volumes:
      - ./kong_data:/var/lib/postgresql/data
    ports:
      - 5301:5432
    restart: always

  konga:
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - konga-container
    container_name: konga
    image: pantsel/konga
    ports:
      - 8082:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=konga-db-container
      - DB_USER=$KONGA_POSTGRES_USER
      - DB_PASSWORD=$KONGA_POSTGRES_PASSWORD
    restart: on-failure:3
    depends_on:
      - konga-db

  konga-db:
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - konga-db-container
    container_name: konga-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=$KONGA_POSTGRES_DB
      - POSTGRES_USER=$KONGA_POSTGRES_USER
      - POSTGRES_PASSWORD=$KONGA_POSTGRES_PASSWORD
    volumes:
      - ./konga_data:/var/lib/postgresql/data
    ports:
      - 5302:5432
    restart: always

networks:
  reverse-proxy-network:
    external: true